### ISSUE TITLE
Hi, met some problems when generating texture for custom meshes.

### ISSUE THREAD

**Issue by Colezwhy** [LIU-Yuxin/SyncMVD#14]
Thank you for your great job!
But I met the following problem when trying to load my glb mesh and generate texture, would you give me some suggestions on that?
![image](https://github.com/LIU-Yuxin/SyncMVD/assets/96565109/b1c4fc19-6db2-4f66-8ee8-bed2ac5bf4c4)

**Comment by Colezwhy** [comment]
Or could you please provide some suggestions on the input mesh format? My original mesh is in ply format, but I converted it into glb format.

**Comment by Colezwhy** [comment]
Sorry for repetitive bothering.
Is it possible that the only input is an .obj file?
Also, When changing the text prompt in the demo configs, I don't see any differences between prompts.

**Comment by Colezwhy** [comment]
![textured_views_rgb](https://github.com/LIU-Yuxin/SyncMVD/assets/96565109/41b8dd72-f049-482f-95a0-7d351a35231d)
The generated texture is like this, it seems that this cannot be correct.

**Comment by LIU-Yuxin** [comment]
The input object is assumed to have only one mesh, and only one material, and a valid UV mapping (enable auto-uv if the UV of original object has overlaps). You can manually cleanup the object in blender. I will also post a blender script for cleanup later.

**Comment by Colezwhy** [comment]
> The input object is assumed to have only one mesh, and only one material, and a valid UV mapping (enable auto-uv if the UV of original object has overlaps). You can manually cleanup the object in blender. I will also post a blender script for cleanup later.

Thank you, but would you please look at the image I shared above? Is the generated texture for the demo 'face' valid?

**Comment by LIU-Yuxin** [comment]
No, it is not. Are you just running the current program without any change?

**Comment by Colezwhy** [comment]
> No, it is not. Are you just running the current program without any change?

Yes, for sure. And for the two demos they are all like this.

**Comment by LIU-Yuxin** [comment]
I will check the output when I incorporate some new changes into the code later, I will fix it if I can reproduce the bug. But there is no guarantee that the program will also work on a different system and environment setup.

**Comment by Colezwhy** [comment]
> I will check the output when I incorporate some new changes into the code later, I will fix it if I can reproduce the bug. But there is no guarantee that the program will also work on a different system and environment setup.

Sure, thank you very much. 
And below is my system and environments.
OS: Ubuntu 18.04
GPU platform: RTX3090 24G
conda package environment: the same as provided readme, pytorch3d used command 'pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu117_pyt201/download.html'

**Comment by LIU-Yuxin** [comment]
I did not find any problem causing this issue when I update the code recently. I wonder if it is related to the UV of the object. Maybe you can pull the latest version and check whether you are running with auto UV enabled.

**Comment by Colezwhy** [comment]
> I did not find any problem causing this issue when I update the code recently. I wonder if it is related to the UV of the object. Maybe you can pull the latest version and check whether you are running with auto UV enabled.

Thank you, I have found the problem, it's like after I have cleaned up the huggingface storage and run the script again, it functioned well again. I am closing this.
Thank you for that again.
