### ISSUE TITLE
triangle faces

### ISSUE THREAD

**Issue by icedCoffe001** [LIU-Yuxin/SyncMVD#3]
nice work！I want to know why i should keep the number of triangle faces within around 40,000?

**Comment by LIU-Yuxin** [comment]
The pytorch3D module uses a set of rules to allocate the buffers, which might not be enough when the mesh has too many triangles. I have not investigated very much on how to refine the rules to support mesh with more triangles, but instead set it statically to a number that seemed to work well for mesh less than 40000, and at the same time don't hurt the speed.
When the buffer is overwhelmed, you will see missing faces as the face list get truncated.

**Comment by icedCoffe001** [comment]
thanks a lot！
